fix(workflows): filtrado de commits
La política de commits se cumplirán en las ramas de develop y main

diff --git a/.github/workflows/commits.yml b/.github/workflows/commits.yml
--- a/.github/workflows/commits.yml
+++ b/.github/workflows/commits.yml
@@ -2,7 +2,7 @@ name: Commits Syntax Checker
 
 on:
   pull_request:
-    branches: [main]
+    branches: [main, develop]
     types: [opened, reopened, edited, review_requested, synchronize]
   push:
     branches:
@@ -20,9 +20,14 @@ jobs:
       - name: Validate Commit Description Length
         run: |
           git log -n 10 --pretty=format:"%H" | while read -r hash; do
-            body=$(git show -s --format=%b $hash) # Obtener solo el cuerpo del commit
+            body=$(git show -s --format=%b $hash) 
             description_length=${#body}
-            if [[ $description_length -gt 500 ]]; then
-              echo "Error: The body of commit $hash exceeds 500 characters." && exit 1
+
+            if [[ -z "$body" ]]; then
+              echo "Error: La descripción del commit $hash está vacía." && exit 1
+            fi
+
+            if [[ $description_length -gt 1000 ]]; then
+              echo "Error: La descripción del commit  $hash supera los 1000 caracteres." && exit 1
             fi
           done
