fix(workflows): filtrado de pull requests v2
He arreglado un error que tenía dicho filtrado

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -4,37 +4,36 @@ on:
   pull_request:
     branches:
       - develop
+      - main
 
 jobs:
   validar-descripcion-pull-request:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Validar descripción de la Pull Request
-        shell: bash  
+      - name: Validar que la descripción no esté vacía
         run: |
-          
-          titulo="${{ github.event.pull_request.title }}"
-          descripcion="${{ github.event.pull_request.body }}"
-
-          
-          if [[ -z "$descripcion" ]]; then
-            echo "Error: La descripción de la Pull Request está vacía." && exit 1
-          fi
-
-          
-          longitud=${#descripcion}
-          if [[ $longitud -gt 1000 ]]; then
-            echo "Error: La descripción de la Pull Request supera los 1000 caracteres." && exit 1
-          fi
-
-          
-          if [[ ! "$titulo" =~ ^(feat|fix|docs|style|refactor|test|chore|perf|build|ci)\([a-zA-Z0-9 _-]+\):\ .+ ]]; then
-            echo "Error: El título de la Pull Request no sigue el formato esperado."
-            echo "Formato esperado: <tipo>(<módulo>): <descripción>"
-            echo "Ejemplo válido: fix(workflows): Corrección en el pipeline de CI"
-            echo "Título actual: '$titulo'"
+          if [[ -z "${{ github.event.pull_request.body }}" ]]; then
+            echo "Error: La descripción de la Pull Request está vacía."
             exit 1
           fi
 
-          echo "La descripción y el título de la Pull Request son válidos."
+      - name: Validar que la descripción no supere 1000 caracteres
+        run: |
+          if [[ ${#github.event.pull_request.body} -gt 1000 ]]; then
+            echo "Error: La descripción de la Pull Request supera los 1000 caracteres."
+            exit 1
+          fi
+
+      - name: Validar el formato del título
+        run: |
+          if ! echo "${{ github.event.pull_request.title }}" | grep -Eq '^(feat|fix|docs|style|refactor|test|chore|perf|build|ci)\([a-zA-Z0-9 _-]+\):\ .+'; then
+            echo "Error: El título de la Pull Request no sigue el formato esperado."
+            echo "Formato esperado: <tipo>(<módulo>): <descripción>"
+            echo "Ejemplo válido: fix(workflows): Corrección en el pipeline de CI"
+            echo "Título actual: '${{ github.event.pull_request.title }}'"
+            exit 1
+          fi
+
+      - name: Validación exitosa
+        run: echo "La descripción y el título de la Pull Request son válidos."
